use automation;
create table user(id int auto_increment primary key,name varchar(34));
insert into user(name) values('deeksha');
select * from dik2;
truncate table user;
desc dik2;
insert into dik2 values(1, 'sunil','sunil@gmail.com', '7854213698', 'sunil123');
select * from dik2;
insert into dik2 values(2, 'kavya','kavya@gmail.com', '4563210458', 'kav123');
select * from dik2;
select name,email from dik2;
select * from dik2 where id=1;
update dik2 set name='Aman' where id=1;
select * from dik2;
delete from dik2 where id=2;
select * from dik2;
insert into dik2 values(2, 'kavya','kavya@gmail.com', '4563210458', 'kav123');
select * from dik2;
select max(id) from dik2;
select min(id) from dik2;
select count(id) from dik2;
select sum(id) from dik2;
use automation;
create table dik3(id int(20), name varchar(50), email varchar(40), mobile varchar(30), pass varchar(34));
select * from dik3;
use automation;
insert into dik3 values(1, 'sunil','sunil@gmail.com', '7854213698', 'sunil123');
select * from dik3;
insert into dik3 values(3, 'diksha','diksah@gmail.com', '8520147856', 'dik123');
select * from dik3;
delete from dik3 where  name='sunil';
DELETE FROM dik3 WHERE emil='sunil@gmail.com';
delete from dik3 where id='1';
select * from dik3;
alter table dik3 modify sunil varchar(50);
delete from dik3;
use automation;

delete from dik3;
select * from dik3;
delete from dik3 where id='1';
delete from dik3;
select * from dik1;
select * from dik3;
insert into dik1 values(1, 'Aman','aman@gmail.com', '86587965423', 'aman123');
select * from dik1;
select dik1.email, dik1.name, dik3.name, dik3.email from dik1 inner join dik3 on dik1.id=dik3.id;
select * from dik3;
use automation;
select * from dik3;